/**
 * Author: Meng
 * Date: 2024/12/03
 * Modify: 2024/12/03
 * Desc:
 */

/**
 * 打开系统分享
 */
export function openSysShare() {
  // let data: systemShare.SharedData = new systemShare.SharedData({
  //   utd: utd.UniformDataType.PLAIN_TEXT,
  //   content: 'Hello HarmonyOS'
  // });
  //
  // let controller: systemShare.ShareController = new systemShare.ShareController(data);
  // // 获取UIAbility上下文对象
  // let context: common.UIAbilityContext = getContext(this) as common.UIAbilityContext;
  // controller.show(context, {
  //   previewMode: systemShare.SharePreviewMode.DETAIL,
  //   selectionMode: systemShare.SelectionMode.SINGLE
  // });
}